---
# Main site playbook for lab infrastructure
# Monitor server (brain + probe) | Backend/Salome = app servers only.

- name: Monitor Server (brain + probe)
  hosts: monitoring
  become: yes
  roles:
    - common
    - node_exporter
    - prometheus
    - loki
    - grafana
    - alertmanager
    - blackbox_exporter

- name: Application Servers (backend + salome)
  hosts: backend,salome
  become: yes
  roles:
    - common
    - node_exporter
    - promtail

- name: Backend Server (apps only)
  hosts: backend
  become: yes
  roles:
    - nginx
  tasks:
    - name: Deploy Python applications
      include_role:
        name: python_app
      vars:
        app_name: "{{ item.name }}"
        app_port: "{{ item.port }}"
        app_repo_url: "{{ item.repo_url }}"
        app_branch: "{{ item.branch }}"
        app_description: "{{ item.description }}"
        app_base_dir: "{{ item.app_base_dir | default(omit) }}"
        app_extra_dirs: "{{ item.app_extra_dirs | default([]) }}"
      loop: "{{ python_apps }}"

- name: Salome Server (apps only)
  hosts: salome
  become: yes
  roles:
    - nginx
  tasks:
    - name: Deploy Salome applications
      include_role:
        name: python_app
      vars:
        app_name: "{{ item.name }}"
        app_port: "{{ item.port }}"
        app_repo_url: "{{ item.repo_url }}"
        app_branch: "{{ item.branch }}"
        app_description: "{{ item.description }}"
        app_base_dir: "{{ item.app_base_dir | default(omit) }}"
        app_extra_dirs: "{{ item.app_extra_dirs | default(omit) }}"
      loop: "{{ python_apps }}"
