# - hosts: all
#   roles:
#     - common

# - hosts: backend:salome
#   roles:
#     - node_exporter

- hosts: salome
  roles:
    - prometheus
    - salome_fastapi
    - promtail

- hosts: backend
  roles:
    - loki
    - grafana
    - promtail_backend